// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(grunt) {
    grunt.initConfig({
      pkg: grunt.file.readJSON('package.json'),
      coffee: {
        compile: {
          options: {
            bare: true,
            sourceMap: true
          },
          expand: true,
          flatten: false,
          cwd: 'src',
          src: ['**/*.coffee'],
          dest: './',
          ext: '.js'
        }
      },
      watch: {
        coffee: {
          files: ['src/**/*.coffee'],
          tasks: ['compile']
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-coffee');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.registerTask('compile', ['coffee']);
    grunt.registerTask('dev', ['compile', 'watch']);
    return grunt.registerTask('default', ['compile']);
  };

}).call(this);
